### PR TITLE
Automated docker container builds via actions

### PR DESCRIPTION
**Pull request by robotdjman**
Creates two docker images: serge-api, and serge-webui available by the ghcr.io repo tied to this repository.
NOTE: Make sure to create a "release" branch where major releases get pulled into as this is what triggers the automated builds. Seems they changed how some GitHub variables worked so took a little trial and error.

### CODE REVIEW

**Comment by robotdjman** [comment]
Creates two docker images: serge-api, and serge-webui available by the ghcr.io repo tied to this repository. 
NOTE: Make sure to create a "release" branch where major releases get pulled into as this is what triggers the automated builds. Seems they changed how some GitHub variables worked so took a little trial and error.

**Comment by nsarrazin** [comment]
This looks super cool, wow, thanks a lot!

I'll give it a good review after work, I really appreciate you doing this.

**Comment by robotdjman** [comment]
Thanks! It was mentioned in #15 but someone will probably have to update the Dockerfiles so that they are built fully self contained (except for volume mounts for the models), I can take a look later tonight!

**Comment by nsarrazin** [comment]
Hey thanks for the contribution! I'll merge it and see if it works.

**Pull request merged**
