### PR TITLE
Implementing deletion of chat

### PR DESCRIPTION
**Pull request by mavaa**
Obligatory PSA that I've never worked with Svelte, FastAPI or beanie, so feel free to tell me how this should be done the correct way 🙃

### CODE REVIEW

**Comment by nsarrazin** [comment]
Thanks a lot! Looks good and indeed a feature that we need.

I'll review it tomorrow, really appreciate the effort.

**Comment by nsarrazin** [comment]
Suggested edit:
```diff
diff --git a/web/src/routes/+layout.svelte b/web/src/routes/+layout.svelte
index 245a83b..6724dd6 100644
--- a/web/src/routes/+layout.svelte
+++ b/web/src/routes/+layout.svelte
@@ -1,39 +1,24 @@
 <script lang="ts">
   import "../app.css";
   import type { LayoutData } from "./$types";
-  import { onMount, afterUpdate } from 'svelte';
+  import { invalidate, goto } from "$app/navigation";
+  import { page } from "$app/stores";
   export let data: LayoutData;
 
-  $: deleteIcon = "&#128465;";
   $: deleteConfirm = false;
-  $: currentChatID = "";
 
-  onMount(refreshCurrent);
-  afterUpdate(refreshCurrent);
-
-  function refreshCurrent() {
-    if(window.location.pathname.startsWith("/chat/")) {
-      var urlPaths = window.location.pathname.split("/");
-      currentChatID = urlPaths[urlPaths.length-1];
-    }
-    else {
-      currentChatID = "";
+  async function deleteChat(chatID: string) {
+    var response = await fetch("/api/chat/" + chatID, { method: "DELETE" });
+    if (response.status == 200) {
+      await goto("/");
+      await invalidate("/api/chats");
+    } else {
+      alert("Error " + response.status + ": " + response.statusText);
     }
   }
 
-  async function deleteChat(chatID) {
-      var response = await fetch("/api/chat/" + chatID, { method: 'DELETE'});
-      if(response.status == 200) {
-        window.location = "/";
-      }
-      else {
-        alert("Error " + response.status + ": " + response.statusText);
-      }
-  }
-
   function toggleDeleteConfirm() {
-      deleteConfirm = !deleteConfirm;
-      deleteIcon = deleteConfirm ? "&#9932;" : "&#128465;";
+    deleteConfirm = !deleteConfirm;
   }
 
   function timeSince(datestring: string) {
@@ -89,20 +74,31 @@
               <div>
                 <span class="font-semibold">{chat.model}</span>
                 <span class="ml-3">{timeSince(chat.created) + " ago"}</span>
-                    {#if currentChatID == chat.id}
-                        {#if deleteConfirm}
-                            <button
-                                class="btn btn-link btn-sm"
-                                on:click|preventDefault={() => deleteChat(chat.id)} >
-                                &#128504;
-                            </button>
-                        {/if}
-                        <button
-                            class="btn btn-link btn-sm"
-                            on:click|preventDefault={toggleDeleteConfirm} >
-                            {@html deleteIcon}
-                        </button>
-                    {/if}
+                {#if $page.params.id == chat.id}
+                  {#if deleteConfirm}
+                    <button
+                      name="confirm-delete"
+                      class="btn btn-ghost btn-sm"
+                      on:click|preventDefault={() => deleteChat(chat.id)}
+                    >
+                      ✅
+                    </button>
+                    <button
+                      name="cancel-delete"
+                      class="btn btn-ghost btn-sm"
+                      on:click|preventDefault={toggleDeleteConfirm}
+                    >
+                      ❎
+                    </button>
+                  {:else}
+                    <button
+                      class="btn btn-ghost btn-sm"
+                      on:click|preventDefault={toggleDeleteConfirm}
+                    >
+                      🗑️
+                    </button>
+                  {/if}
+                {/if}
               </div>
               <p class="font-light text-sm">{truncate(chat.subtitle, 100)}</p>
             </div>

```

**Comment by nsarrazin** [comment]
So this came from VSCode, not sure if it's easily appliable.

The API endpoint works really great I did refactor the svelte front-end a bit. Here are the most important changes:

- I used `goto`, `invalidate` and `$page.params` which are built-in svelte kit feature for navigation, invalidating data and accessing url parameters respectively. This makes the code a bit simpler and more "svelte-ic"? 
- I got rid of a few superfluous reactive variables that were not needed.

If you agree with those changes, let me know and feel free to apply them, otherwise it looks really good and it's a much needed feature, thanks for contributing!

**Comment by nsarrazin** [comment]
Gonna merge it with the refactoring haha, it's a wanted feature so I'm doing it now.

**Review by nsarrazin — APPROVED** [review]

**Comment by mavaa** [comment]
That's great, thanks for fixing! 😃

**Pull request merged**
