### PR TITLE
Prebuilt compose file, Buildx caching, readme updates

### PR DESCRIPTION
**Pull request by robotdjman**
Added a compose file that uses the GitHub container registry to get the latest build including some readme documentation, @manudiv16 added builds support for caching.

### CODE REVIEW

**Comment by nsarrazin** [comment]
Hey @robotdjman ! Thanks for making this. I was thinking about this since we also now have an example of integration with kubernetes in #71. 

I'd like to move the integration examples with `docker compose`  and `kubernetes` to the wiki, so the code repo can be focused on the serge image itself.

I think they're quite good examples but since they don't contribute directly to building the image, I think they belong more in the wiki. What do you think ?

**Comment by robotdjman** [comment]
@nsarrazin Oh yeah if we are getting a wiki setup that is definitely the way to go. The build caching would be something to pull into release (dropped builds from 2.5 minutes to 30 seconds). I don't believe there is a way to just not pull the readme commit [c7521d6](https://github.com/nsarrazin/serge/pull/70/commits/c7521d65a53c7f5cbd6f2eedef51a6e1d60b57ed) right?

**Comment by gaby** [comment]
@robotdjman Can you fix the merge conflicts? Awesome work!

**Review by gaby — APPROVED** [review]

**Comment by robotdjman** [comment]
Fixed the merge and removed the added documentation of using the prebuilt docker compose file since it will be added to the wiki later.

**Comment by gaby** [comment]
@nsarrazin This one should be good to merge

**Comment by gaby** [comment]
@robotdjman I'd say to make those last changes in a separate PR to get this one merged.

**Pull request closed without merging**
