### PR TITLE
Initial support for Kubernetes

### PR DESCRIPTION
**Pull request by FenarkSEC**
I have made this manifest and managed to make it work on a self-hosted Kubernetes v1.25.6 environment with the service exposed as a LoadBalancer type. Should also work as NodePort.

serge-ai-k8s

I built the image from the Dockerfile and pushed it to my private repo. Adding an official Docker image would be better in order to have a proper container image lifecycle. 

In the meantime, I have put placeholder variables that can be changed later.

### CODE REVIEW

**Comment by FenarkSEC** [comment]
After some tests I changed the content of web/vite.config.ts, it doesn't seem to have an impact when deploying on Docker.

I've just seen that a container image has been pushed on ghcr.io.
However I am facing an issue with that image (look for https://github.com/nsarrazin/serge/issues/72) which can be easily fixed with the solution provided in the issue.

**Comment by nsarrazin** [comment]
Nice, I really like having support for this.

May I ask that we keep the fixes needed for compatibility in the PR plus the readme explanation, but maybe we could move the manifest itself to the wiki with a link in the readme ?

I would like the code repo to be focused on building the serge image and move examples of integrations, (with docker compose or kubernetes) to the wiki, with the appropriate links in the readme.

**Comment by nsarrazin** [comment]
I made a wiki page: https://github.com/nsarrazin/serge/wiki/Integrating-Serge-in-your-orchestration, not sure if you can also edit it ?

**Comment by FenarkSEC** [comment]
Sure, I see no problem in putting the manifest in the wiki and remove it from the repo :)

I have tried pushing my commit but I get a 403.

**Comment by nsarrazin** [comment]
> Sure, I see no problem in putting the manifest in the wiki and remove it from the repo :)
> 
> I have tried pushing my commit for the wiki but I get a 403.

Can you try again ?

**Comment by FenarkSEC** [comment]
It works, thank you !

**Comment by nsarrazin** [comment]
Thank you, very cool! I'll make sure this PR doesn't break things on my end and approve afterwards.

**Review by nsarrazin — APPROVED** [review]
Works great! Approving.

**Comment by FenarkSEC** [comment]
It's alright, I should mention in the wiki that it is possible to edit the PVC size as well as the StorageClass used and the mode. I'm using an NFS StorageClass which allows the cluster to mount multiple pods to the same volume (ReadWriteMany mode).
I'm guessing I should put as default ReadWriteOnce in the wiki so more people would be able to use Serge without encountering incompatibilities with the SC they use.

**Pull request merged**
