### PR TITLE
Web UI/UX improvements

### PR DESCRIPTION
**Pull request by pabl-o-ce**
Add favicon.png
Home: Serge svg icon from Discord
Navbar: Colors and svg icons.
Chat: Avatars svg icons, header and input style

### CODE REVIEW

**Comment by gaby** [comment]
@pabl-o-ce Whats the source/license for the llama icon?

**Comment by pabl-o-ce** [comment]
> @pabl-o-ce Whats the source/license for the llama icon?

Llama by The Icon Z from <a href="https://thenounproject.com/browse/icons/term/llama/" target="_blank" title="Llama Icons">Noun Project</a>

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-04-25 at 10 32 56 PM

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-04-25 at 10 57 08 PM
Screen Shot 2023-04-25 at 10 57 54 PM
Screen Shot 2023-04-25 at 10 58 19 PM

Screen Shot 2023-04-25 at 10 58 50 PM
Screen Shot 2023-04-25 at 10 59 07 PM

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-04-26 at 9 21 09 AM
loading

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-04-28 at 3 05 02 AM

MD render and copy to clipboard

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-04-28 at 4 02 49 AM

code block background adapts to themes

**Comment by nsarrazin** [comment]
Ok I'm reviewing this for real now I promise

**Comment by nsarrazin** [comment]
I'm currently reviewing it, it's quite a big PR so in the future I think it would be better to break up changes into multiple PRs.

For example for this one you could have broken it up into:
- Restyling of the chat bubbles & sidebar
- Change in icons
- Adding code blocks in answer
- Adding copy button to code blocks

They could all have been separate PRs which would have made it easier to get it through the review process, as I can review, approve or request changes on smaller chunks, one at a time :smile: 

I also think it's good practice to file an issue before starting a PR (for big changes), that way we can discuss it before you spend too much time working on something where maybe we're not aligned on the requirements.

Otherwise it's a great PR, thanks a lot, especially the code blocks are amazing. I'm taking the liberty to refactor some stuff here and there in the PR and I will merge it when I'm done. Thanks again for the contribution and sorry it's taking so long!

**Comment by pabl-o-ce** [comment]
Hi @nsarrazin 

Thanks for accepting the PR.

I think it was a inspiration moment in your discord channel and also getting feedback from there (meeting great people in your channel).

Really wanted to help, contribute and just enter in that mode.

I apologize if the PR was all included in one and also without generating a issue as a normal person will do it. Love the idea to have a discord channel for a popular project so people can get related to it. I think that lost me in generating the issue and follow the good practice.

If you need to change something or don't go with the aligned of your idea feel free to change it [my intentions was for help]. All just began when I just wanted to learn svelte with your project as a starting point and also learn to use Llama.cpp with Python. The avatar icons can be very inappropriate or just don't wanted at all.

Thanks for this amazing idea! 🙂

**Comment by gaby** [comment]
May want to rebase the branch 😁

**Comment by gaby** [comment]
@nsarrazin @pabl-o-ce Whats the plan with this PR? It would make serge look way better!

**Comment by pabl-o-ce** [comment]
Hi @gaby, 

Yes I want to keep contributing 🙂

Just waiting to @nsarrazin to finish integrating this PR

I think he is busy of what it told us in chat [I'm just waiting patient]

**Comment by gaby** [comment]
@pabl-o-ce Can you fix the merge conflicts

**Comment by gaby** [comment]
@pabl-o-ce any idea?

**Comment by pabl-o-ce** [comment]
@gaby and @greenfoo this changes are only on the front-end.. I think is because of the changes on ggml of llama.cpp

**Comment by pabl-o-ce** [comment]
Screen Shot 2023-05-24 at 10 03 08 AM

test it haha let me refresh my models (in this one I'm using theBloke) https://huggingface.co/TheBloke

**Comment by pabl-o-ce** [comment]
@gaby done I remove it a put it like this 
Screen Shot 2023-05-24 at 10 31 27 PM

**Pull request merged**
