### PR TITLE
Make it useable

### PR DESCRIPTION
**Pull request by rakete**
This is a nice project, but it currently has problems that prevent it from being useable imho. These have been present for a while too:  
https://github.com/nsarrazin/serge/issues/219
https://github.com/nsarrazin/serge/issues/133

I can see how issue 219 should be fixed using the langchain tokenizer, but no one really did that yet as far as I can tell.

Instead of trying to come up with the proper solution, I just spend a sunday afternoon to hack something together that works well enough so I can have a conversation with a LLM inside serge. This is what this PR contains. I just needed to do this the dirty way to get an understanding what is actually going on.

You can of course merge this if you want, or maybe take it as inspiration, I just wanted to share it with anyone who might be interested.

Warning: this adds a new field to Chat.params, which are serialized and stored (in redis? in some browser local storage?). This change can potentially break your existing chats.

### CODE REVIEW

**Comment by rakete** [comment]
wizard-vicuna

Works nicely now, takes the history into account and doesn't run over the token limit all the time.

**Comment by nsarrazin** [comment]
Thanks for contributing, I'll have a look!

**Comment by kolabearafk** [comment]
@rakete How did you get Wizard-Vicuna-13B to work as shown in the previous image you attached? Was it added by you or does Serge support that model now?? Please help.

**Comment by rakete** [comment]
You can just put the Wizard-Vicuna model by TheBloke into the models directory and then select it. You can get it here: https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML/tree/main

Also for everyone else still looking at this, I actually noticed I made some mistakes in this PR, for example I didn't realize that these "### System" etc. guys actually have a point. I thought I could just remove them, so I did (at least the ### System one). It does work fine without it as far as I can tell and it saves a bit of context size, but it should still be added back.

**Comment by rakete** [comment]
If you don't know how to "put the model into the directory": you can mount any directory when you launch serge, it is this parameters: `-v weights:/usr/src/app/weights`, change that to something like `-v /some/local/directory:/usr/src/app/weights` and then put your models into `/some/local/directory`.

You can also edit the docker-compose.yml file and change the volume section to mount a local dir:
```
volumes:
      - datadb:/data/db
      - /some/local/directory:/usr/src/app/weights/
      - /etc/localtime:/etc/localtime:ro
```
like so ^

**Comment by gaby** [comment]
@rakete it would need to point to TheBloke models right?

**Comment by rakete** [comment]
@gaby that's what I used, also see my edit cause you need to get the ggml files until you updated llama to the latest version, which then needs ggmlv3

**Comment by koalaeagle** [comment]
I was about to give up on serge but adding these changes did as stated: made it useable! Thanks for your efforts.

**Comment by gaby** [comment]
@rakete Main branch now uses ggmlv3

**Comment by gaby** [comment]
@rakete Can you fix the merge conflicts so we can merge this :-)

**Comment by rakete** [comment]
@gaby just saw this message, I'll fix them

**Comment by rakete** [comment]
@gaby I had to fiddle with it and figure out how to run serge again since I had not touched it in a while, but everything merged and testing locally worked fine. So should be good to go.

If you want I can make a followup PR where I add back the System prompt thing.

**Comment by gaby** [comment]
@rakete The format/lint checks are failing. These are done using `black` and `ruff`.

**Pull request merged**
