### PR TITLE
When a user hits CTRL+ENTER send input

### PR DESCRIPTION
**Pull request by snxraven**
Tested this and it seems OK.

This allows users to hit CTRL+ENTER to send chat input :)

### CODE REVIEW

**Comment by gourcetools** [comment]
This is cool

**Comment by NortySpock** [comment]
Worked in my testing. Certainly more convenient once you get used to it.

**Comment by snxraven** [comment]
I added fixes to the Input Text and send button. On mobile these elements would cover up chat bubbles so you were unable to read what the AI was responding back. This fixes the issues completely by fixing these elements to the bottom of the page with some adjusting of sizing to make it all fit. If this can be done better, let me know :)

**Review by gaby — APPROVED** [review]
LGTM

**Comment by nsarrazin** [comment]
Looks and works great thank you! I added a small margin to the input field at the bottom so they don't hug the bottom of the window, but other than that, great work, I'm merging it.

**Review by nsarrazin — APPROVED** [review]

**Pull request merged**
