### PR TITLE
Correctly pass the context window length

### PR DESCRIPTION
**Pull request by johncadengo**
Working on https://github.com/nsarrazin/serge/issues/133

In the view it was named `ctx_length` but the controller expected `context_window`

- Update name to `context_window`

### CODE REVIEW

**Comment by johncadengo** [comment]
@nsarrazin I need some help on fixing Issue #133. The commit I have so far allows me to adjust the context window, but I'm not sure how to ensure that the prompt being given does not exceed the maximum number of tokens when being passed to the generator. Can you point me in the right direction or help me with this PR?

**Comment by nsarrazin** [comment]
Good catch! I'll merge this PR as is to get the bugfix in there. 

I think it's not a trivial change to make sure the number of tokens doesn't exceed the max allowed size. I'm working on a PR that uses llama.cpp interactive mode to handle chats so hopefully that will fix the issue. Thank you contributing!

**Review by nsarrazin — APPROVED** [review]

**Comment by voarsh2** [comment]
Have I missed anything? Because after a few chats, I still get 

```
RETURN CODE 1

main: seed = 1680733988
llama_model_load: loading model from '/usr/src/app/weights/ggml-vicuna-13b-4bit-rev1.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx = 512
llama_model_load: n_embd = 5120
llama_model_load: n_mult = 256
llama_model_load: n_head = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot = 128
llama_model_load: f16 = 2
llama_model_load: n_ff = 13824
llama_model_load: n_parts = 1
llama_model_load: type = 2
llama_model_load: ggml map size = 7759.84 MB
llama_model_load: ggml ctx size = 101.25 KB
llama_model_load: mem required = 9807.93 MB (+ 1608.00 MB per state)
llama_model_load: loading tensors from '/usr/src/app/weights/ggml-vicuna-13b-4bit-rev1.bin'
llama_model_load: model size = 7759.40 MB / num tensors = 363
llama_init_from_file: kv self size = 400.00 MB

system_info: n_threads = 8 / 32 | AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
main: error: prompt is too long (771 tokens, max 508)
```

**Comment by johncadengo** [comment]
@voarsh2 this PR addresses the ability to adjust the context window size. It correctly lets you adjust it from the UI now. However, it doesn't make sure the prompt fits within that window. 

There's an open PR that addresses it here: PR #140.

However, it seems that @nsarrazin has indicated that PR #140 might not be necessary and might be superseded by this PR here: PR #143. 

#143 seems like a big change that will improve lots of functionality.

**Pull request merged**
