### PR TITLE
main.py now recursively looks for .bin files.

### PR DESCRIPTION
**Pull request by axolotlite**
I've modified the line responsible for finding .bin files inside weights to recursively look for .bin files.

### CODE REVIEW

**Comment by gaby** [comment]
@axolotlite Can you fix conflicts, and merge main into your branch? Thanks

**Comment by axolotlite** [comment]
@gaby I've modified routers/model.py to recursively look for .bin files while maintaining compatibility with the already existing download_models.
nested .bin files will now be displayed under the downloaded models if possible.
image
I've also tested chatting with the models.
downloadable model placed in $WEIGHTS/7B.bin
image
manually mounted models inside $WEIGHTS.
image
a picture from the download models tab in the web ui.
image

**Review by gaby — APPROVED** [review]
LGTM!

**Comment by gaby** [comment]
@nsarrazin Can you review this?

**Review by nsarrazin — APPROVED** [review]
Seems to be working well! :+1: Thank you for the contribution.

**Pull request merged**
